/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f9f9fc",
        foreground: "#1a1c1e",
        "on-background": "#1a1c1e",
        surface: "#f9f9fc",
        "surface-bright": "#f9f9fc",
        "surface-dim": "#dadadc",
        "surface-gray": "#F8F9FA",
        "surface-tint": "#006b5e",
        "surface-variant": "#e2e2e5",
        "surface-container": "#eeeef0",
        "surface-container-low": "#f3f3f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8ea",
        "surface-container-highest": "#e2e2e5",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#3e4946",
        primary: "#005147",
        "primary-foreground": "#ffffff",
        "primary-container": "#006b5e",
        "primary-fixed": "#9ff2e1",
        "primary-fixed-dim": "#83d5c5",
        "on-primary": "#ffffff",
        "on-primary-container": "#95e8d8",
        "on-primary-fixed": "#00201b",
        "on-primary-fixed-variant": "#005046",
        "growth-green": "#006B5E",
        secondary: "#006d2f",
        "secondary-foreground": "#ffffff",
        "secondary-container": "#5dfd8a",
        "secondary-fixed": "#66ff8e",
        "secondary-fixed-dim": "#3de273",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007232",
        "on-secondary-fixed": "#002109",
        "on-secondary-fixed-variant": "#005322",
        tertiary: "#003fa3",
        "tertiary-container": "#0055d4",
        "tertiary-fixed": "#dae2ff",
        "tertiary-fixed-dim": "#b2c5ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ccd8ff",
        "on-tertiary-fixed": "#001848",
        "on-tertiary-fixed-variant": "#003fa3",
        "trust-blue": "#0055D4",
        error: "#ba1a1a",
        "error-foreground": "#ffffff",
        "error-container": "#ffdad6",
        "error-red": "#BA1A1A",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        border: "#e2e2e5",
        "border-subtle": "#E1E3E5",
        muted: "#6e7976",
        "muted-foreground": "#3e4946",
        outline: "#6e7976",
        "outline-variant": "#bec9c5",
        "inverse-surface": "#2f3133",
        "inverse-on-surface": "#f0f0f3",
        "inverse-primary": "#83d5c5",
        "status-pending": "#FEF7FF",
        "status-shipped": "#F0FDF4"
      },
      borderRadius: {
        DEFAULT: 4,
        sm: 4,
        md: 8,
        lg: 8,
        xl: 12,
        "2xl": 16,
        "3xl": 24,
        full: 9999
      },
      spacing: {
        "stack-sm": 8,
        "stack-md": 16,
        "stack-lg": 32,
        "margin-mobile": 20,
        "gutter-mobile": 16,
        "touch-target-min": 48
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro"],
        "headline-lg-mobile": ["Be Vietnam Pro"],
        "headline-md": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"],
        "label-lg": ["Be Vietnam Pro"],
        "label-sm": ["Be Vietnam Pro"]
      },
      fontSize: {
        "headline-lg": 32,
        "headline-lg-mobile": 28,
        "headline-md": 24,
        "body-lg": 18,
        "body-md": 16,
        "label-lg": 14,
        "label-sm": 12
      }
    }
  },
  plugins: [],
};
